### ISSUE TITLE
2.4. feladat: Szerver tervezése

### ISSUE THREAD

**Issue by thayol** [nagytoth1/oprendszerek_beadando#3]
A 2.4.-nél az alap információk részleg teljesen hiányzik, egyből a 2.4.1. következik a `h2` után.

https://github.com/nagytoth1/oprendszerek_beadando/blob/0a865bdc716236a4b3aecf360741fc70f775031b/dokumentacio.md?plain=1#L210-L212

Itt felsorolva 3 nagyon alap információt a szerverről, illetve valami extrával (például backup strategy) a végén meglenne a maximális pont.

A releváns hivatalos pontozási részleg:
> * 1 pont / alap információ a szerver(ek) ről (max 3 pont)
> * 1 kiegészítő szolgáltatások (mentés, monitorozás) leírása
> * 0.5 pont / egyéb fel nem sorolt, de a feladat szempontjából lényegesnek tűnő terv (max 2 pont)

*Megjegyzés: Az összes alpont elvégzése többletpontokat nem eredményez. Elég a hiányzó **2 pontot** behozni.*

**Comment by nagytoth1** [comment]
A d84c1ee commitban hozzáadtuk a szervertervezés bevezető szövegét
