### ISSUE TITLE
2.5. feladat: Kliens tervezése

### ISSUE THREAD

**Issue by thayol** [nagytoth1/oprendszerek_beadando#4]
Érdemes lenne a lokális felhasználókról és a fájlrendszerről írni egy pár szót. Ha mást nem, akkor csak megemlíteni, hogy milyen, hogy eltér-e az alapértelmezett Windows telepítéstől, illetve hogy milyen felhasználó lesz használva a telepítési procedúrához.

https://github.com/nagytoth1/oprendszerek_beadando/blob/0a865bdc716236a4b3aecf360741fc70f775031b/dokumentacio.md?plain=1#L292-L299

A hivatalos pontozás a következő:
> Összesen max 5 pont
> * 0,5 / pont alap információk (max 1,5 pont)
> * 3 pont a használandó / telepítendő szolgáltatások és alkalmazások
> * 2 pont lokális felhasználók
> * 2 pont fájlrendszer
> * (plusz) 1 pont / egyéb fel nem sorolt, de a feladat szempontjából lényegesnek tűnő terv (max 2 pont)

**Comment by nagytoth1** [comment]
A 653a116 commitban hozzáadtuk a kliensek telepítésének tervezett folyamatát.
