### ISSUE TITLE
2.6. és 4. feladat: Tesztelési terv és tesztelés

### ISSUE THREAD

**Issue by thayol** [nagytoth1/oprendszerek_beadando#5]
25 teszt van dokumentálva. Az esetek jók, viszont a feladat legalább 30 tesztet ír elő.

https://github.com/nagytoth1/oprendszerek_beadando/blob/0a865bdc716236a4b3aecf360741fc70f775031b/dokumentacio.md?plain=1#L328

https://github.com/nagytoth1/oprendszerek_beadando/blob/0a865bdc716236a4b3aecf360741fc70f775031b/dokumentacio.md?plain=1#L482

**Comment by nagytoth1** [comment]
572c238 comittal hozzáadtunk további 5 tesztesetet a teszt tervhez és a teszteléshez is.
A teszteket holnap elvégezzük, eredményüket a táblázatba beírjuk

**Comment by nagytoth1** [comment]
A maradék 5 teszteset eredményét beírtam, ez a legutóbbi, 02fc24e commitban látható.

**Comment by thayol** [comment]
Javítósdi is van benne, kiváló!
